{
    parserClass="com.asdhammu.cspdrogon.language.parser.CSPDrogonParser"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="CSPDrogon"
    psiImplClassSuffix="Impl"
    psiPackage="com.asdhammu.cspdrogon.language.psi"
    psiImplPackage="com.asdhammu.cspdrogon.language.psi.impl"

    elementTypeHolderClass="com.asdhammu.cspdrogon.language.psi.CSPDrogonTypes"
    elementTypeClass="com.asdhammu.cspdrogon.language.psi.CSPDrogonElementType"
    tokenTypeClass="com.asdhammu.cspdrogon.language.psi.CSPDrogonTokenType"

    tokens = [
        FILE_NAME="regexp:[a-zA-Z][a-zA-Z0-9_-]*"
        PARAM_VARIABLE_NAME="regexp:[a-zA-Z][a-zA-Z0-9_-]*"
        VIEW_START='<%view'
        LAYOUT_START='<%layout'
        DIRECTIVE_END='%>'
        CSP_EXT='.csp'
        WHITE_SPACE='regexp:\s+'
        PARAM_START='[['
        PARAM_END=']]'
    ]
}

CSPDirectiveFile ::= item_*

private item_ ::= (csp_directive|OTHER)

csp_directive ::= view_directive | layout_directive | param_directive

view_directive ::= VIEW_START WHITE_SPACE* FILE_NAME CSP_EXT WHITE_SPACE* DIRECTIVE_END

layout_directive ::= LAYOUT_START WHITE_SPACE* FILE_NAME CSP_EXT WHITE_SPACE* DIRECTIVE_END

param_directive ::= PARAM_START WHITE_SPACE* PARAM_VARIABLE_NAME WHITE_SPACE* PARAM_END